name: Build and Deploy Docker Image

on:
  push:
    branches: [ release ]

env:
  DB: ${{ secrets.DB }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and save Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }} \
            --build-arg DB=$DB \
            --build-arg DB_USER=$DB_USER \
            --build-arg DB_PASSWORD=$DB_PASSWORD \
            .
          docker save ${{ secrets.IMAGE_NAME }} > "${{ secrets.IMAGE_NAME }}.tar"
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ secrets.IMAGE_NAME }}
          path: "${{ secrets.IMAGE_NAME }}.tar"

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ secrets.IMAGE_NAME }}.tar"
          target: /root/containers/

      - name: Start new container using the new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop ${{ secrets.IMAGE_NAME }}
            docker rm ${{ secrets.IMAGE_NAME }}
            docker load < "/root/containers/${{ secrets.IMAGE_NAME }}.tar"
            docker run -d --name ${{ secrets.IMAGE_NAME }} -p 3306:3306 ${{ secrets.IMAGE_NAME }}
            exit